### PR TITLE
add qt version info to about dialog

### PR DESCRIPTION
**Pull request by timsurber**
This is so that I don't get confused when testing and also could help debugging user issues.

image

### CODE REVIEW

**Comment by rumengb** [comment]
I do not think qt version is relevant. What is the reason to have it in the about dialog? I was about to remove it from the qt6_port branch.

**Comment by rumengb** [comment]
> This is so that I don't get confused when testing and also could help debugging user issues.

In that case, we will keep it in the QT6 branch and then move it to the log. About dialog is not about debugging :)

**Comment by rumengb** [comment]
Sorry I will not accept this. I will keep it in the qt6 branch until we witch but after that I will remove it. No offense please.
It will look like this :) 
image

**Comment by timsurber** [comment]
No problem, I think your solution is fine!

**Pull request closed without merging**
