### PR TITLE
Revert "List resources in qrc files"

### PR DESCRIPTION
**Pull request by rumengb**
Reverts indigo-astronomy/indigo_imager#23

This does not work! resources are missing from Ain. Not a single icon is visible!

### CODE REVIEW

**Comment by timsurber** [comment]
Interesting.
https://github.com/timsurber/indigo_imager/actions/runs/10728945428

Does this link work for you and can you download the artifacts?
I just build this based on the latest master with the resource changes for Linux/AMD64 and I can see all icons.

On Win11 System it also works.

**Comment by rumengb** [comment]
Sorry, No offence but I have made my decision, I will not accept any qt
modernization PRs in the master. Please send them to the qt6_port.

**Comment by timsurber** [comment]
Should I resend them or will you merge them into qt6_port?
Should I continue with these smaller PRs or collect it?

**Comment by rumengb** [comment]
Please do small commits and you can make PRs with several comments.

As it is now it is not easy to merge master in to qt6_port as there are
conflicts and I am on vacation. So I will make new branch tonight from the
master and you should apply all the Qt 6 changes and keep this branch in
track with master. I have things to do in indigo right now a s I will not
be very active committing to Ain.

**Comment by rumengb** [comment]
Please send prs to qt6 branch

**Pull request merged**
